# Generated by Django 4.1 on 2023-01-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loggedIn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostAdmin',
        ),
    ]
